### ISSUE TITLE
nmos-testing not starting (2)

### ISSUE THREAD

**Issue by marcograt** [rhastie/easy-nmos#19]
Hi there, 

i have an issue with starting the easy-nmos docker images. As stated in the readme, in my docker-compose-file i adjusted the ip-addresses for the nmos instances and also the external network but docker complains:

ERROR: for nmos-registry  Cannot start service nmos-registry: Invalid address 10.0.230.101: It does not belong to any of this network's subnets.

```
-- excerpt from the compose-file: --
networks:
    external:
      # Create external macvlan subnet using host physical interface allowing containers to have their own IP addresses
      driver: macvlan
      driver_opts:
          parent: eno1
      ipam:
          config:
          - subnet: 10.0.0.0/8
-- snip --
```

The hosts ethernet has the 10.0.12.9/8. 

Any ideas?

Regards, Marco

**Comment by rhastie** [comment]
Please can you send your whole YAML file and also the IP addresses you'd like the 3 containers to appear on...

Generally there are 3 things you need to set:
1. Make sure "parent" above matches with you interface name that you want to use - You appear to have changed this from the default so I think this is correct
2. Make sure your subnet is configured correctly. Again I think that is correct based on above
3. Define Static IP addresses for each of the containers - You need to set this 3 times, one for each of the containers that run - Please look for the 3 "ipv4_address" entries in the YAML

**Comment by rhastie** [comment]
Actually there is a 4th thing you should check...

Interface eno1 should have a subnet and IP address assigned to it that's compatible with your YAML file. ie. The IP address on interface eno1 should have a subnet of 10.0.0.0/8 and a IP address in the range 10.x.x.x. This IP address should be different to the 3 static ones you are assigning in the YAML.

**Comment by marcograt** [comment]
Hello again and thanks for the quick response. 


version: '3.6'

```
services:

  # Create NMOS Registry/Controller container instance
  nmos-registry:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-registry
    hostname: nmos-registry
    domainname: local
    ports:
    - "3080-3081:80-81"
    - "4883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    networks: 
      external:
        ipv4_address: '10.0.230.101'

  # Create NMOS Virtual Node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode
    domainname: local
    ports:
    - "3080-3081:80-81"
    volumes:
    - "./node.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      external:
        ipv4_address: '10.0.230.111.102'
    depends_on:
    - nmos-registry    

  # Create AMWA NMOS Testing container instance
  nmos-testing:
    image: amwa/nmos-testing:latest
    container_name: nmos-testing
    hostname: nmos-testing
    domainname: local
    entrypoint: |
       /bin/bash -c "/etc/init.d/dbus start;
       /etc/init.d/avahi-daemon start;
       python3 nmos-test.py"
    ports:
    - "5000:5000"
    volumes:
    - "./UserConfig.py:/config/UserConfig.py"
    networks:
      external:
        ipv4_address: '10.0.230.103'
    depends_on:
    - nmos-virtnode


networks:
    external:
      # Create external macvlan subnet using host physical interface allowing containers to have their own IP addresses
      driver: macvlan
      driver_opts:
          parent: eno1
      ipam:
          config:
          - subnet: 10.0.0.0/8

```

ip addr show eno1

```
eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
    inet 10.0.12.9/8 brd 10.255.255.255 scope global dynamic noprefixroute eno1
       valid_lft 2137sec preferred_lft 2137sec
    inet6 XXXX::XXXX:XXXX:XXXX:XXXX64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

The docker version is 20.10.12, build 20.10.12-0ubuntu2~20.04.1

Kindly,
Marco
